version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: service-db
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres2"
      POSTGRES_PASSWORD: "passwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    expose:
      - "5435"
    networks:
      - test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  web-service:
    image: mariafarfan/dockerimage_flask_app:latest
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    container_name: app2
    links:
      - postgres:postgres
    networks:
      - test
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: "service-db"
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres2"
      POSTGRES_PASSWORD: "passwd"

networks:
  test:
    driver: bridge